apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: animus
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.client | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: animus-client-svc
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.admin | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: animus-admin-svc
                port:
                  number: 80
