apiVersion: v1
kind: Secret
metadata:
  name: animus-secrets
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ required "secrets.mysqlPassword is required" .Values.secrets.mysqlPassword | quote }}
  TMDB_API_KEY: {{ .Values.secrets.tmdbApiKey | quote }}
  TMDB_ACCESS_TOKEN: {{ .Values.secrets.tmdbAccessToken | quote }}
