apiVersion: apps/v1
kind: Deployment
metadata:
  name: animus-admin
spec:
  selector:
    matchLabels:
      app: animus-admin
  template:
    metadata:
      labels:
        app: animus-admin
    spec:
      nodeSelector:
        role: application
      containers:
        - name: animus-admin
          image: abstergo07/animus-admin:latest
          env:
            - name: API_UPSTREAM
              value: http://animus-api-svc:4000
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: animus-admin-svc
spec:
  selector:
    app: animus-admin
  ports:
    - port: 80
      targetPort: 80
